"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2019 Storj Labs, Inc.
See LICENSE for copying information.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CipherSuite:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CipherSuiteEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CipherSuite.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENC_UNSPECIFIED: _CipherSuite.ValueType  # 0
    ENC_NULL: _CipherSuite.ValueType  # 1
    ENC_AESGCM: _CipherSuite.ValueType  # 2
    ENC_SECRETBOX: _CipherSuite.ValueType  # 3

class CipherSuite(_CipherSuite, metaclass=_CipherSuiteEnumTypeWrapper): ...

ENC_UNSPECIFIED: CipherSuite.ValueType  # 0
ENC_NULL: CipherSuite.ValueType  # 1
ENC_AESGCM: CipherSuite.ValueType  # 2
ENC_SECRETBOX: CipherSuite.ValueType  # 3
global___CipherSuite = CipherSuite

@typing_extensions.final
class EncryptionParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CIPHER_SUITE_FIELD_NUMBER: builtins.int
    BLOCK_SIZE_FIELD_NUMBER: builtins.int
    cipher_suite: global___CipherSuite.ValueType
    block_size: builtins.int
    def __init__(
        self,
        *,
        cipher_suite: global___CipherSuite.ValueType = ...,
        block_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["block_size", b"block_size", "cipher_suite", b"cipher_suite"]) -> None: ...

global___EncryptionParameters = EncryptionParameters
