# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uplink/common/pb/encryption_access.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from uplink.common.pb import encryption_pb2 as uplink_dot_common_dot_pb_dot_encryption__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(uplink/common/pb/encryption_access.proto\x12\x11\x65ncryption_access\x1a!uplink/common/pb/encryption.proto\"\xba\x03\n\x10\x45ncryptionAccess\x12\x13\n\x0b\x64\x65\x66\x61ult_key\x18\x01 \x01(\x0c\x12\x45\n\rstore_entries\x18\x02 \x03(\x0b\x32..encryption_access.EncryptionAccess.StoreEntry\x12\x34\n\x13\x64\x65\x66\x61ult_path_cipher\x18\x03 \x01(\x0e\x32\x17.encryption.CipherSuite\x12G\n\x1d\x64\x65\x66\x61ult_encryption_parameters\x18\x04 \x01(\x0b\x32 .encryption.EncryptionParameters\x1a\xca\x01\n\nStoreEntry\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x0c\x12\x18\n\x10unencrypted_path\x18\x02 \x01(\x0c\x12\x16\n\x0e\x65ncrypted_path\x18\x03 \x01(\x0c\x12\x0b\n\x03key\x18\x04 \x01(\x0c\x12,\n\x0bpath_cipher\x18\x05 \x01(\x0e\x32\x17.encryption.CipherSuite\x12?\n\x15\x65ncryption_parameters\x18\x06 \x01(\x0b\x32 .encryption.EncryptionParametersB\x14Z\x12storj.io/common/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uplink.common.pb.encryption_access_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022storj.io/common/pb'
  _globals['_ENCRYPTIONACCESS']._serialized_start=99
  _globals['_ENCRYPTIONACCESS']._serialized_end=541
  _globals['_ENCRYPTIONACCESS_STOREENTRY']._serialized_start=339
  _globals['_ENCRYPTIONACCESS_STOREENTRY']._serialized_end=541
# @@protoc_insertion_point(module_scope)
