"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2019 Storj Labs, Inc.
See LICENSE for copying information.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import uplink.common.pb.encryption_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EncryptionAccess(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class StoreEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BUCKET_FIELD_NUMBER: builtins.int
        UNENCRYPTED_PATH_FIELD_NUMBER: builtins.int
        ENCRYPTED_PATH_FIELD_NUMBER: builtins.int
        KEY_FIELD_NUMBER: builtins.int
        PATH_CIPHER_FIELD_NUMBER: builtins.int
        ENCRYPTION_PARAMETERS_FIELD_NUMBER: builtins.int
        bucket: builtins.bytes
        unencrypted_path: builtins.bytes
        encrypted_path: builtins.bytes
        key: builtins.bytes
        path_cipher: uplink.common.pb.encryption_pb2.CipherSuite.ValueType
        @property
        def encryption_parameters(self) -> uplink.common.pb.encryption_pb2.EncryptionParameters: ...
        def __init__(
            self,
            *,
            bucket: builtins.bytes = ...,
            unencrypted_path: builtins.bytes = ...,
            encrypted_path: builtins.bytes = ...,
            key: builtins.bytes = ...,
            path_cipher: uplink.common.pb.encryption_pb2.CipherSuite.ValueType = ...,
            encryption_parameters: uplink.common.pb.encryption_pb2.EncryptionParameters | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["encryption_parameters", b"encryption_parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["bucket", b"bucket", "encrypted_path", b"encrypted_path", "encryption_parameters", b"encryption_parameters", "key", b"key", "path_cipher", b"path_cipher", "unencrypted_path", b"unencrypted_path"]) -> None: ...

    DEFAULT_KEY_FIELD_NUMBER: builtins.int
    STORE_ENTRIES_FIELD_NUMBER: builtins.int
    DEFAULT_PATH_CIPHER_FIELD_NUMBER: builtins.int
    DEFAULT_ENCRYPTION_PARAMETERS_FIELD_NUMBER: builtins.int
    default_key: builtins.bytes
    @property
    def store_entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EncryptionAccess.StoreEntry]: ...
    default_path_cipher: uplink.common.pb.encryption_pb2.CipherSuite.ValueType
    @property
    def default_encryption_parameters(self) -> uplink.common.pb.encryption_pb2.EncryptionParameters: ...
    def __init__(
        self,
        *,
        default_key: builtins.bytes = ...,
        store_entries: collections.abc.Iterable[global___EncryptionAccess.StoreEntry] | None = ...,
        default_path_cipher: uplink.common.pb.encryption_pb2.CipherSuite.ValueType = ...,
        default_encryption_parameters: uplink.common.pb.encryption_pb2.EncryptionParameters | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["default_encryption_parameters", b"default_encryption_parameters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["default_encryption_parameters", b"default_encryption_parameters", "default_key", b"default_key", "default_path_cipher", b"default_path_cipher", "store_entries", b"store_entries"]) -> None: ...

global___EncryptionAccess = EncryptionAccess
