# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uplink/common/pb/scope.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from uplink.common.pb import encryption_access_pb2 as uplink_dot_common_dot_pb_dot_encryption__access__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cuplink/common/pb/scope.proto\x12\x05scope\x1a(uplink/common/pb/encryption_access.proto\"p\n\x05Scope\x12\x16\n\x0esatellite_addr\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\x0c\x12>\n\x11\x65ncryption_access\x18\x03 \x01(\x0b\x32#.encryption_access.EncryptionAccessB\x14Z\x12storj.io/common/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uplink.common.pb.scope_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022storj.io/common/pb'
  _globals['_SCOPE']._serialized_start=81
  _globals['_SCOPE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
