"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2019 Storj Labs, Inc.
See LICENSE for copying information.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import uplink.common.pb.encryption_access_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Scope(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SATELLITE_ADDR_FIELD_NUMBER: builtins.int
    API_KEY_FIELD_NUMBER: builtins.int
    ENCRYPTION_ACCESS_FIELD_NUMBER: builtins.int
    satellite_addr: builtins.str
    api_key: builtins.bytes
    @property
    def encryption_access(self) -> uplink.common.pb.encryption_access_pb2.EncryptionAccess: ...
    def __init__(
        self,
        *,
        satellite_addr: builtins.str = ...,
        api_key: builtins.bytes = ...,
        encryption_access: uplink.common.pb.encryption_access_pb2.EncryptionAccess | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["encryption_access", b"encryption_access"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_key", b"api_key", "encryption_access", b"encryption_access", "satellite_addr", b"satellite_addr"]) -> None: ...

global___Scope = Scope
